apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: project-management-app
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: YWRtaW4=  # 'admin' encoded in base64
  POSTGRES_PASSWORD: YWRtaW4=          # 'admin' encoded in base64
