apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: project-management-app
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30090
